name: vox-schismaticus
on:
  push:
    branches:
      - item/*

jobs:
  workflow:
    runs-on: buildjet-2vcpu-ubuntu-2204

    steps:
      - name: checkout
        uses: actions/checkout@v2.3.2

      - name: install ffmpeg
        run: |
          sudo apt-get update
          sudo apt-get install ffmpeg


      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.5'

      - name: pip install
        uses: BSFishy/pip-action@v1
        with:
          packages: |
            youtube-dl
            spleeter

      - name: download youtube video
        run: |
          source initial-variable.sh
          youtube-dl $YOUTUBE_URL -o video.mp4 --recode-video mp4
          echo $(ls video*) > RAW_VIDEO_FILE_NAME

      - name: convert to video to audio
        run: |
          ffmpeg -y -i $(cat RAW_VIDEO_FILE_NAME) audio.mp3

      - name: split audio to vocal and instrument
        run: |
          export TEMP_GITHUB_REPOSITORY=$GITHUB_REPOSITORY
          export GITHUB_REPOSITORY=deezer/spleeter
          spleeter separate -i audio.mp3 -o audio_output
          export GITHUB_REPOSITORY=$TEMP_GITHUB_REPOSITORY

      - name: convert vocal and instrument audio files to mono
        run: |
          ffmpeg -y -i audio_output/audio/accompaniment.wav -map_channel 0.0.0 left.wav
          ffmpeg -y -i audio_output/audio/vocals.wav -map_channel 0.0.1 right.wav

      - name: merge audio to different stream
        run: ffmpeg -y -i left.wav -i right.wav -filter_complex "[0:a][1:a]amerge=inputs=2[a]" -map "[a]" final.mka

      - name: add audio to video
        run: ffmpeg -y -i $(cat RAW_VIDEO_FILE_NAME) -i final.mka -map 0:0 -map 1:0 -c:v copy -c:a aac -b:a 256k -shortest final-$(cat RAW_VIDEO_FILE_NAME)

      - name: upload to file hosting and push the generated url
        run: |
          curl -F file=@final-$(cat RAW_VIDEO_FILE_NAME) -F expires=3d https://api.anonymousfiles.io/ |  jq '.url' > final-url
          git config --global user.email "kristiantokarim@gmail.com"	
          git config --global user.name "Kristianto"
          git reset 
          git add final-url
          git commit -m "Add generated url"
          git push origin HEAD
          
      
